/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.apache.thrift.TException;
import org.apache.thrift.protocol.TProtocol;
import org.apache.thrift.transport.TSocket;

/**
 *
 * @author mrrobot
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    Login login;
    TSocket transport;
    TProtocol protocol;
    Juego.Client juego;
    Tiempo tiempo;
    int nivel;

    public Tablero(TSocket transport, TProtocol protocol, Juego.Client juego,Login login) {
        this.transport = transport;
        this.protocol = protocol;
        this.juego = juego;
        initComponents();
        graficaNiveles();
        this.setBounds(100, 100, 1010, 550);
        this.login = login;
        jButton2.setEnabled(false);
    }

    public void graficaNiveles() {
        //graficar niveles
        try {
            jLabel7.setText(juego.getCantGemas()+"");
            juego.graficarNiveles();
        } catch (TException ex) {
            Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
        }
        String path = "/home/mrrobot/Documentos/2486034770301@ingenieria.usac.edu.gt/Estructuras/Laboratorio/Proyecto1EDD/build-Servidor-Desktop-Debug/niveles.png";
        ImageIcon icon = new ImageIcon(path);
        icon.getImage().flush();
        jLabel2.setIcon(icon);
        jLabel5.setText("0");
        jTextField4.setText("201503823Cheats");
        jLabel11.setText("00:00");
        try {
            jLabel7.setText(juego.getCantGemas()+"");
        } catch (TException ex) {
            Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BATTLE JAM");
        setBackground(new java.awt.Color(51, 51, 51));
        setBounds(new java.awt.Rectangle(100, 100, 994, 514));
        getContentPane().setLayout(null);

        jLabel1.setText("Niveles");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(51, 6, 60, 15);

        jLabel3.setText("Seleccionar Nivel");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(289, 6, 120, 15);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(197, 60, 93, 23);

        jButton1.setText("Iniciar Juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(308, 56, 170, 31);

        jLabel4.setText("Punteo");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(502, 6, 51, 15);

        jLabel5.setFont(new java.awt.Font("Sidney Demo Rough", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("0");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(490, 50, 83, 40);

        jLabel6.setText("Gemas");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(670, 6, 48, 15);

        jLabel7.setFont(new java.awt.Font("Sidney Demo Rough", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("0");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(647, 50, 83, 40);

        jTextField2.setFont(new java.awt.Font("Sidney Demo Rough", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 51, 51));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(340, 430, 45, 48);

        jLabel8.setText("X:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 430, 26, 48);

        jLabel9.setText("Y:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(400, 430, 26, 48);

        jTextField3.setFont(new java.awt.Font("Sidney Demo Rough", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 51, 51));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(420, 430, 45, 48);

        jButton2.setFont(new java.awt.Font("Sidney Demo Rough", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("ATAQUE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(479, 420, 230, 64);

        jLabel10.setText("Tiempo:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(198, 108, 56, 15);

        jLabel11.setFont(new java.awt.Font("Sidney Demo Rough", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 255, 204));
        jLabel11.setText("00:00");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(272, 96, 117, 37);

        jLabel12.setText("Cheat's:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(840, 0, 59, 26);

        jTextField4.setFont(new java.awt.Font("always  forever", 1, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("201503823Cheats");
        jTextField4.setToolTipText("");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(740, 40, 245, 32);

        jButton3.setText("Activar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(728, 90, 130, 31);

        jLabel13.setText("Desactivado");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(880, 100, 87, 15);

        jLabel14.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(720, 420, 270, 64);

        jScrollPane1.setViewportView(jLabel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 160, 450);

        jButton4.setText("Canjear Gema");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(570, 90, 150, 31);

        jMenu1.setText("Juego");

        jMenuItem1.setText("Salir De usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Recargar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Punteo");

        jMenuItem2.setText("Punteo General");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Arbol de Punteo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!jTextField1.getText().isEmpty()) {
            try {
                nivel = Integer.parseInt(jTextField1.getText());
                if (juego.seleccionarNivel(nivel)) {
                    jButton2.setEnabled(true);
                    tiempo = new Tiempo(jLabel11, nivel, juego, jButton1,jLabel7,jButton2);
                    jLabel7.setText(juego.getCantGemas() + "");
                    JOptionPane.showMessageDialog(null, "Iniciando el juego");
                    tiempo.start();
                    jButton1.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(null, "El nivel esta bloqueado o no existe");
                }
            } catch (TException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No se seleccion ningun nivel valido");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(jLabel13.getText().equals("Desactivado"))
        {
            jLabel13.setText("Activado");
            jButton3.setText("Desactivar");
        }
        else
        {
            jLabel13.setText("Desactivado");
            jButton3.setText("Activar");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (!jTextField2.getText().isEmpty() && !jTextField3.getText().isEmpty()) {
            try {
                int x = Integer.parseInt(jTextField2.getText());
                int y = Integer.parseInt(jTextField3.getText());
                if (juego.atacar(x, y)) {
                    jLabel14.setText("Baja Confirmada");
                } else {
                    jLabel14.setText("Baja Sin confirmar");
                }
                jLabel5.setText(juego.getPunteo() + "");
            } catch (TException ex) {
                Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CanGema cangem = new CanGema(juego);
        cangem.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        graficaNiveles();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
            juego.graficarPunteoLista();
        } catch (TException ex) {
            Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            // TODO add your handling code here:
            juego.graficarPunteoArbol();
        } catch (TException ex) {
            Logger.getLogger(Tablero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
