// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.
#include "hiloapache.h"
#include "niveles.h"
#include "Juego.h"
#include <iostream>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::Servidor;

HiloApache::HiloApache(Niveles *nivel)
{
    this->nivel = nivel;
}

class JuegoHandler : virtual public JuegoIf {
 public:
    Niveles *nivel;
  JuegoHandler(Niveles *nivel) {
    this->nivel = nivel;
  }

  bool crearUsuario(const std::string& nombre) {
    cout << "Recibiendo nombre de usuario..."<<endl;
      return nivel->crearUsuario(nombre);
  }

  bool seleccionarNivel(const int32_t nivel) {
      cout << "Recibiendo nivel a jugar"<<endl;
    return this->nivel->Jugar(nivel);
  }

  bool atacar(const int32_t x, const int32_t y) {
    return nivel->atacar(x,y);
  }

  int32_t getPunteo() {
      cout << "Retornando puteo"<<endl;
      return nivel->getPunteo();
    }

  bool graficarEnemigosEliminados() {
    nivel->graficarLisEnemigosElim();
    cout << "Graficando listas de enemigos eliminados"<<endl;
  }

  bool cheats(const std::string& cheat) {
    cout <<"Activando Cheats"<<endl;
    nivel->onOffCheat();
  }

  bool DesbloquearNiveleGema(const int32_t nivel) {
      cout<<"Desbloqueando nivel con gema"<<endl;
    return this->nivel->desbloquearNivelGema(nivel);
  }

  bool graficarPunteoLista() {
    nivel->graficarLisUsuario();
    cout << "Graficando lista de punteos general"<<endl;
  }

  bool graficarPunteoArbol() {
    nivel->graficarArbol();
    cout << "Graficando arbol de punteos"<<endl;
  }

  bool pausar() {
    nivel->pausar();
    cout <<"pausando la creacion y movimiento de enemigos"<<endl;
  }

  void setMin(const int32_t min) {
    nivel->min = min;
    cout <<"Seteando minitos de juego"<<endl;
  }

  void setSeg(const int32_t seg) {
    nivel->seg = seg;
    cout <<"seteando segundos de juego"<<endl;
  }

  void finalizar() {
      //nivel->graficarLisEnemigosElim();
      nivel->finjuego();
      cout << "Fin del juego"<<endl;
    }

  int32_t getCantGemas() {
       cout <<"Retronando cantidad de Gemas"<<endl;
      return nivel->getCantGemas();
    }

    bool buscarUsuario(const std::string& nombre) {
        cout <<"buscando usuario..."<<endl;
      return nivel->buscarUsuario(nombre);
    }

    bool ganoNivel() {
      cout <<"Verificando punteo con nivel"<<endl;
      nivel->ganoNivel();
    }

    void graficarNiveles() {
      cout <<"Graficando niveles"<<endl;
      nivel->graficarNiveles();
    }
};

void HiloApache::run()
{
    int port = 9090;
    ::apache::thrift::stdcxx::shared_ptr<JuegoHandler> handler(new JuegoHandler(this->nivel));
    ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new JuegoProcessor(handler));
    ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
    server.serve();
}

