/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Servidor_constants.h"

namespace Servidor {

const ServidorConstants g_Servidor_constants;

ServidorConstants::ServidorConstants() {
}

} // namespace

